image:
  tag: 23.0.7-debian-12-r5

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.dittmeister.de
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"  # Optional
  tls: true
  extraTls:
    - hosts:
        - keycloak.dittmeister.de
      secretName: keycloak-tls

proxy: edge

auth:
  adminUser: admin
  adminPassword: admin